version: "3.9"
services:
  dl-myo:
    build: .
    image: ghcr.io/iomz/dl-myo:latest
    container_name: dl-myo
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myo
      - DOCKER_INFLUXDB_INIT_PASSWORD=super-secret
      - DOCKER_INFLUXDB_INIT_ORG=dl-myo
      - DOCKER_INFLUXDB_INIT_BUCKET=myo
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-auth-token
    volumes:
      - $PWD/examples/influxdb/data:/var/lib/influxdb2
      - $PWD/examples/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
